apiVersion: v1
kind: Service
metadata:
  name: {{ include "libero-editor.fullname" . }}-client
  labels:
    app.kubernetes.io/name: {{ include "libero-editor.name" . }}
    helm.sh/chart: {{ include "libero-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: client
spec:
  type: ClusterIp
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "libero-editor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: client