# Default values for libero-editor.

ingress:
  host: libero-editor--staging.elifesciences.org
  client:
    path: /
  articleStore:
    path: /api/v1(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

client:
  image:
    repository: liberoadmin/editor-client
    tag: latest
    pullPolicy: Always
  port: 80
  replicaCount: 1

articleStore:
  image:
    repository: liberoadmin/editor-article-store
    tag: latest
    pullPolicy: Always
  port: 8080
  replicaCount: 1

database:
  endpoint: 'mongo:27017'
  query: ''
  # database.secret -- name of a secret with 'user' and 'password' entries
  secret: libero-editor--database-secret
  sslValidate: 'true'
  name: 'editor'

aws:
  region: 'us-east-1'
  # aws.secret -- name of a secret with 'key' and 'secret' entries
  secret: libero-editor--aws-secret
  sqsUrl: ''
  bucket: 'prod-elife-editor'
