# Default values for libero-editor.

ingress:
  host: libero-editor--staging.elifesciences.org
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  client:
    path: /
  articleStore:
    path: /api/v1(/|$)(.*)

client:
  image:
    repository: liberoadmin/editor-client
    tag: latest
    pullPolicy: Always
  port: 80
  replicaCount: 1

articleStore:
  image:
    repository: liberoadmin/editor-article-store
    tag: latest
    pullPolicy: Always
  port: 8080
  replicaCount: 1