name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: validate
        uses: elifesciences/helm-validator-action@master
        with:
          chartPath: 'helm/libero-editor'
